/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.generator.node;

import java.util.*;
import scss.generator.analysis.*;

@SuppressWarnings("nls")
public final class AStylesheet extends PStylesheet
{
    private final LinkedList<PRuleset> _ruleset_ = new LinkedList<PRuleset>();

    public AStylesheet()
    {
        // Constructor
    }

    public AStylesheet(
        @SuppressWarnings("hiding") List<?> _ruleset_)
    {
        // Constructor
        setRuleset(_ruleset_);

    }

    @Override
    public Object clone()
    {
        return new AStylesheet(
            cloneList(this._ruleset_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStylesheet(this);
    }

    public LinkedList<PRuleset> getRuleset()
    {
        return this._ruleset_;
    }

    public void setRuleset(List<?> list)
    {
        for(PRuleset e : this._ruleset_)
        {
            e.parent(null);
        }
        this._ruleset_.clear();

        for(Object obj_e : list)
        {
            PRuleset e = (PRuleset) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._ruleset_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ruleset_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ruleset_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PRuleset> i = this._ruleset_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PRuleset) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
