/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.generator.analysis;

import scss.generator.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAStylesheet(AStylesheet node);
    void caseARuleRuleset(ARuleRuleset node);
    void caseAPropertyRuleset(APropertyRuleset node);
    void caseABlock(ABlock node);

    void caseTColon(TColon node);
    void caseTLBrace(TLBrace node);
    void caseTRBrace(TRBrace node);
    void caseTSemicolon(TSemicolon node);
    void caseTIdentifier(TIdentifier node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
