/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.calculation.node;

import java.util.*;
import scss.calculation.analysis.*;

@SuppressWarnings("nls")
public final class AAssigmentStatement extends PStatement
{
    private PVariable _variable_;
    private TColon _colon_;
    private TIdentifier _identifier_;
    private final LinkedList<PCommaIdentifier> _commaIdentifier_ = new LinkedList<PCommaIdentifier>();

    public AAssigmentStatement()
    {
        // Constructor
    }

    public AAssigmentStatement(
        @SuppressWarnings("hiding") PVariable _variable_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") List<?> _commaIdentifier_)
    {
        // Constructor
        setVariable(_variable_);

        setColon(_colon_);

        setIdentifier(_identifier_);

        setCommaIdentifier(_commaIdentifier_);

    }

    @Override
    public Object clone()
    {
        return new AAssigmentStatement(
            cloneNode(this._variable_),
            cloneNode(this._colon_),
            cloneNode(this._identifier_),
            cloneList(this._commaIdentifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssigmentStatement(this);
    }

    public PVariable getVariable()
    {
        return this._variable_;
    }

    public void setVariable(PVariable node)
    {
        if(this._variable_ != null)
        {
            this._variable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variable_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public LinkedList<PCommaIdentifier> getCommaIdentifier()
    {
        return this._commaIdentifier_;
    }

    public void setCommaIdentifier(List<?> list)
    {
        for(PCommaIdentifier e : this._commaIdentifier_)
        {
            e.parent(null);
        }
        this._commaIdentifier_.clear();

        for(Object obj_e : list)
        {
            PCommaIdentifier e = (PCommaIdentifier) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._commaIdentifier_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variable_)
            + toString(this._colon_)
            + toString(this._identifier_)
            + toString(this._commaIdentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variable_ == child)
        {
            this._variable_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._commaIdentifier_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variable_ == oldChild)
        {
            setVariable((PVariable) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        for(ListIterator<PCommaIdentifier> i = this._commaIdentifier_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PCommaIdentifier) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
