/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.calculation.node;

import java.util.*;
import scss.calculation.analysis.*;

@SuppressWarnings("nls")
public final class AAssigmentStatement extends PStatement
{
    private PCommaValue _first_;
    private TColon _colon_;
    private PCommaValue _second_;
    private final LinkedList<PCommaValue> _rest_ = new LinkedList<PCommaValue>();
    private TSemicolon _semicolon_;

    public AAssigmentStatement()
    {
        // Constructor
    }

    public AAssigmentStatement(
        @SuppressWarnings("hiding") PCommaValue _first_,
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PCommaValue _second_,
        @SuppressWarnings("hiding") List<?> _rest_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setFirst(_first_);

        setColon(_colon_);

        setSecond(_second_);

        setRest(_rest_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AAssigmentStatement(
            cloneNode(this._first_),
            cloneNode(this._colon_),
            cloneNode(this._second_),
            cloneList(this._rest_),
            cloneNode(this._semicolon_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssigmentStatement(this);
    }

    public PCommaValue getFirst()
    {
        return this._first_;
    }

    public void setFirst(PCommaValue node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PCommaValue getSecond()
    {
        return this._second_;
    }

    public void setSecond(PCommaValue node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    public LinkedList<PCommaValue> getRest()
    {
        return this._rest_;
    }

    public void setRest(List<?> list)
    {
        for(PCommaValue e : this._rest_)
        {
            e.parent(null);
        }
        this._rest_.clear();

        for(Object obj_e : list)
        {
            PCommaValue e = (PCommaValue) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._rest_.add(e);
        }
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._colon_)
            + toString(this._second_)
            + toString(this._rest_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        if(this._rest_.remove(child))
        {
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PCommaValue) newChild);
            return;
        }

        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((PCommaValue) newChild);
            return;
        }

        for(ListIterator<PCommaValue> i = this._rest_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PCommaValue) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
