/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.calculation.node;

import java.util.*;
import scss.calculation.analysis.*;

@SuppressWarnings("nls")
public final class ACallFunctionCall extends PFunctionCall
{
    private PCommaValue _name_;
    private TLPar _lPar_;
    private PFunctionCall _first_;
    private final LinkedList<PFunctionCall> _second_ = new LinkedList<PFunctionCall>();
    private TRPar _rPar_;

    public ACallFunctionCall()
    {
        // Constructor
    }

    public ACallFunctionCall(
        @SuppressWarnings("hiding") PCommaValue _name_,
        @SuppressWarnings("hiding") TLPar _lPar_,
        @SuppressWarnings("hiding") PFunctionCall _first_,
        @SuppressWarnings("hiding") List<?> _second_,
        @SuppressWarnings("hiding") TRPar _rPar_)
    {
        // Constructor
        setName(_name_);

        setLPar(_lPar_);

        setFirst(_first_);

        setSecond(_second_);

        setRPar(_rPar_);

    }

    @Override
    public Object clone()
    {
        return new ACallFunctionCall(
            cloneNode(this._name_),
            cloneNode(this._lPar_),
            cloneNode(this._first_),
            cloneList(this._second_),
            cloneNode(this._rPar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACallFunctionCall(this);
    }

    public PCommaValue getName()
    {
        return this._name_;
    }

    public void setName(PCommaValue node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public TLPar getLPar()
    {
        return this._lPar_;
    }

    public void setLPar(TLPar node)
    {
        if(this._lPar_ != null)
        {
            this._lPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lPar_ = node;
    }

    public PFunctionCall getFirst()
    {
        return this._first_;
    }

    public void setFirst(PFunctionCall node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public LinkedList<PFunctionCall> getSecond()
    {
        return this._second_;
    }

    public void setSecond(List<?> list)
    {
        for(PFunctionCall e : this._second_)
        {
            e.parent(null);
        }
        this._second_.clear();

        for(Object obj_e : list)
        {
            PFunctionCall e = (PFunctionCall) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._second_.add(e);
        }
    }

    public TRPar getRPar()
    {
        return this._rPar_;
    }

    public void setRPar(TRPar node)
    {
        if(this._rPar_ != null)
        {
            this._rPar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rPar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._lPar_)
            + toString(this._first_)
            + toString(this._second_)
            + toString(this._rPar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._lPar_ == child)
        {
            this._lPar_ = null;
            return;
        }

        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._second_.remove(child))
        {
            return;
        }

        if(this._rPar_ == child)
        {
            this._rPar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((PCommaValue) newChild);
            return;
        }

        if(this._lPar_ == oldChild)
        {
            setLPar((TLPar) newChild);
            return;
        }

        if(this._first_ == oldChild)
        {
            setFirst((PFunctionCall) newChild);
            return;
        }

        for(ListIterator<PFunctionCall> i = this._second_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFunctionCall) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._rPar_ == oldChild)
        {
            setRPar((TRPar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
