/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.calculation.node;

import scss.calculation.analysis.*;

@SuppressWarnings("nls")
public final class ACommaCommaValue extends PCommaValue
{
    private TComma _comma_;
    private PCommaValue _commaValue_;

    public ACommaCommaValue()
    {
        // Constructor
    }

    public ACommaCommaValue(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PCommaValue _commaValue_)
    {
        // Constructor
        setComma(_comma_);

        setCommaValue(_commaValue_);

    }

    @Override
    public Object clone()
    {
        return new ACommaCommaValue(
            cloneNode(this._comma_),
            cloneNode(this._commaValue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommaCommaValue(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PCommaValue getCommaValue()
    {
        return this._commaValue_;
    }

    public void setCommaValue(PCommaValue node)
    {
        if(this._commaValue_ != null)
        {
            this._commaValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._commaValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._commaValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._commaValue_ == child)
        {
            this._commaValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._commaValue_ == oldChild)
        {
            setCommaValue((PCommaValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
