/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.calculation.node;

import scss.calculation.analysis.*;

@SuppressWarnings("nls")
public final class ADollarVariable extends PVariable
{
    private TDollar _dollar_;
    private PVariable _variable_;

    public ADollarVariable()
    {
        // Constructor
    }

    public ADollarVariable(
        @SuppressWarnings("hiding") TDollar _dollar_,
        @SuppressWarnings("hiding") PVariable _variable_)
    {
        // Constructor
        setDollar(_dollar_);

        setVariable(_variable_);

    }

    @Override
    public Object clone()
    {
        return new ADollarVariable(
            cloneNode(this._dollar_),
            cloneNode(this._variable_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADollarVariable(this);
    }

    public TDollar getDollar()
    {
        return this._dollar_;
    }

    public void setDollar(TDollar node)
    {
        if(this._dollar_ != null)
        {
            this._dollar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dollar_ = node;
    }

    public PVariable getVariable()
    {
        return this._variable_;
    }

    public void setVariable(PVariable node)
    {
        if(this._variable_ != null)
        {
            this._variable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variable_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dollar_)
            + toString(this._variable_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dollar_ == child)
        {
            this._dollar_ = null;
            return;
        }

        if(this._variable_ == child)
        {
            this._variable_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dollar_ == oldChild)
        {
            setDollar((TDollar) newChild);
            return;
        }

        if(this._variable_ == oldChild)
        {
            setVariable((PVariable) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
