/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.calculation.node;

import scss.calculation.analysis.*;

@SuppressWarnings("nls")
public final class APercUnit extends PUnit
{
    private PUnit _unit_;
    private TMod _mod_;

    public APercUnit()
    {
        // Constructor
    }

    public APercUnit(
        @SuppressWarnings("hiding") PUnit _unit_,
        @SuppressWarnings("hiding") TMod _mod_)
    {
        // Constructor
        setUnit(_unit_);

        setMod(_mod_);

    }

    @Override
    public Object clone()
    {
        return new APercUnit(
            cloneNode(this._unit_),
            cloneNode(this._mod_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPercUnit(this);
    }

    public PUnit getUnit()
    {
        return this._unit_;
    }

    public void setUnit(PUnit node)
    {
        if(this._unit_ != null)
        {
            this._unit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unit_ = node;
    }

    public TMod getMod()
    {
        return this._mod_;
    }

    public void setMod(TMod node)
    {
        if(this._mod_ != null)
        {
            this._mod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mod_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unit_)
            + toString(this._mod_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unit_ == child)
        {
            this._unit_ = null;
            return;
        }

        if(this._mod_ == child)
        {
            this._mod_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unit_ == oldChild)
        {
            setUnit((PUnit) newChild);
            return;
        }

        if(this._mod_ == oldChild)
        {
            setMod((TMod) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
