/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.calculation.node;

import scss.calculation.analysis.*;

@SuppressWarnings("nls")
public final class TB2s extends Token
{
    public TB2s()
    {
        super.setText("$b2s");
    }

    public TB2s(int line, int pos)
    {
        super.setText("$b2s");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TB2s(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTB2s(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TB2s text.");
    }
}
