/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.calculation.node;

import scss.calculation.analysis.*;

@SuppressWarnings("nls")
public final class TI2s extends Token
{
    public TI2s()
    {
        super.setText("$i2s");
    }

    public TI2s(int line, int pos)
    {
        super.setText("$i2s");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TI2s(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTI2s(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TI2s text.");
    }
}
