/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.calculation.node;

import scss.calculation.analysis.*;

@SuppressWarnings("nls")
public final class TMixin extends Token
{
    public TMixin()
    {
        super.setText("@mixin");
    }

    public TMixin(int line, int pos)
    {
        super.setText("@mixin");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMixin(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMixin(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMixin text.");
    }
}
