/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class ACommaPrefixElement extends PPrefixElement
{
    private TComma _comma_;
    private PPrefixElement _prefixElement_;

    public ACommaPrefixElement()
    {
        // Constructor
    }

    public ACommaPrefixElement(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PPrefixElement _prefixElement_)
    {
        // Constructor
        setComma(_comma_);

        setPrefixElement(_prefixElement_);

    }

    @Override
    public Object clone()
    {
        return new ACommaPrefixElement(
            cloneNode(this._comma_),
            cloneNode(this._prefixElement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommaPrefixElement(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PPrefixElement getPrefixElement()
    {
        return this._prefixElement_;
    }

    public void setPrefixElement(PPrefixElement node)
    {
        if(this._prefixElement_ != null)
        {
            this._prefixElement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prefixElement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._prefixElement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._prefixElement_ == child)
        {
            this._prefixElement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._prefixElement_ == oldChild)
        {
            setPrefixElement((PPrefixElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
