/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class AElseIfStatement extends PElseIfStatement
{
    private TAtElse _atElse_;
    private TIf _if_;
    private PConditions _conditions_;
    private PBlock _block_;

    public AElseIfStatement()
    {
        // Constructor
    }

    public AElseIfStatement(
        @SuppressWarnings("hiding") TAtElse _atElse_,
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") PConditions _conditions_,
        @SuppressWarnings("hiding") PBlock _block_)
    {
        // Constructor
        setAtElse(_atElse_);

        setIf(_if_);

        setConditions(_conditions_);

        setBlock(_block_);

    }

    @Override
    public Object clone()
    {
        return new AElseIfStatement(
            cloneNode(this._atElse_),
            cloneNode(this._if_),
            cloneNode(this._conditions_),
            cloneNode(this._block_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseIfStatement(this);
    }

    public TAtElse getAtElse()
    {
        return this._atElse_;
    }

    public void setAtElse(TAtElse node)
    {
        if(this._atElse_ != null)
        {
            this._atElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atElse_ = node;
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public PConditions getConditions()
    {
        return this._conditions_;
    }

    public void setConditions(PConditions node)
    {
        if(this._conditions_ != null)
        {
            this._conditions_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conditions_ = node;
    }

    public PBlock getBlock()
    {
        return this._block_;
    }

    public void setBlock(PBlock node)
    {
        if(this._block_ != null)
        {
            this._block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._block_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atElse_)
            + toString(this._if_)
            + toString(this._conditions_)
            + toString(this._block_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atElse_ == child)
        {
            this._atElse_ = null;
            return;
        }

        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._conditions_ == child)
        {
            this._conditions_ = null;
            return;
        }

        if(this._block_ == child)
        {
            this._block_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._atElse_ == oldChild)
        {
            setAtElse((TAtElse) newChild);
            return;
        }

        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._conditions_ == oldChild)
        {
            setConditions((PConditions) newChild);
            return;
        }

        if(this._block_ == oldChild)
        {
            setBlock((PBlock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
