/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class AElseStatement extends PElseStatement
{
    private TAtElse _atElse_;
    private PBlock _block_;

    public AElseStatement()
    {
        // Constructor
    }

    public AElseStatement(
        @SuppressWarnings("hiding") TAtElse _atElse_,
        @SuppressWarnings("hiding") PBlock _block_)
    {
        // Constructor
        setAtElse(_atElse_);

        setBlock(_block_);

    }

    @Override
    public Object clone()
    {
        return new AElseStatement(
            cloneNode(this._atElse_),
            cloneNode(this._block_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseStatement(this);
    }

    public TAtElse getAtElse()
    {
        return this._atElse_;
    }

    public void setAtElse(TAtElse node)
    {
        if(this._atElse_ != null)
        {
            this._atElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atElse_ = node;
    }

    public PBlock getBlock()
    {
        return this._block_;
    }

    public void setBlock(PBlock node)
    {
        if(this._block_ != null)
        {
            this._block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._block_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atElse_)
            + toString(this._block_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atElse_ == child)
        {
            this._atElse_ = null;
            return;
        }

        if(this._block_ == child)
        {
            this._block_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._atElse_ == oldChild)
        {
            setAtElse((TAtElse) newChild);
            return;
        }

        if(this._block_ == oldChild)
        {
            setBlock((PBlock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
