/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class AEqComparison extends PComparison
{
    private PComparison _left_;
    private TEqeq _eqeq_;
    private PArith _right_;

    public AEqComparison()
    {
        // Constructor
    }

    public AEqComparison(
        @SuppressWarnings("hiding") PComparison _left_,
        @SuppressWarnings("hiding") TEqeq _eqeq_,
        @SuppressWarnings("hiding") PArith _right_)
    {
        // Constructor
        setLeft(_left_);

        setEqeq(_eqeq_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AEqComparison(
            cloneNode(this._left_),
            cloneNode(this._eqeq_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqComparison(this);
    }

    public PComparison getLeft()
    {
        return this._left_;
    }

    public void setLeft(PComparison node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TEqeq getEqeq()
    {
        return this._eqeq_;
    }

    public void setEqeq(TEqeq node)
    {
        if(this._eqeq_ != null)
        {
            this._eqeq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eqeq_ = node;
    }

    public PArith getRight()
    {
        return this._right_;
    }

    public void setRight(PArith node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._eqeq_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._eqeq_ == child)
        {
            this._eqeq_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PComparison) newChild);
            return;
        }

        if(this._eqeq_ == oldChild)
        {
            setEqeq((TEqeq) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PArith) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
