/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class AGtPrefixElement extends PPrefixElement
{
    private TGt _gt_;
    private PElement _second_;

    public AGtPrefixElement()
    {
        // Constructor
    }

    public AGtPrefixElement(
        @SuppressWarnings("hiding") TGt _gt_,
        @SuppressWarnings("hiding") PElement _second_)
    {
        // Constructor
        setGt(_gt_);

        setSecond(_second_);

    }

    @Override
    public Object clone()
    {
        return new AGtPrefixElement(
            cloneNode(this._gt_),
            cloneNode(this._second_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGtPrefixElement(this);
    }

    public TGt getGt()
    {
        return this._gt_;
    }

    public void setGt(TGt node)
    {
        if(this._gt_ != null)
        {
            this._gt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gt_ = node;
    }

    public PElement getSecond()
    {
        return this._second_;
    }

    public void setSecond(PElement node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._gt_)
            + toString(this._second_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._gt_ == child)
        {
            this._gt_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._gt_ == oldChild)
        {
            setGt((TGt) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((PElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
