/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import java.util.*;
import scss.analysis.*;

@SuppressWarnings("nls")
public final class AListValues extends PListValues
{
    private PExpression _expression_;
    private final LinkedList<PCommaExpression> _commaExpression_ = new LinkedList<PCommaExpression>();

    public AListValues()
    {
        // Constructor
    }

    public AListValues(
        @SuppressWarnings("hiding") PExpression _expression_,
        @SuppressWarnings("hiding") List<?> _commaExpression_)
    {
        // Constructor
        setExpression(_expression_);

        setCommaExpression(_commaExpression_);

    }

    @Override
    public Object clone()
    {
        return new AListValues(
            cloneNode(this._expression_),
            cloneList(this._commaExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListValues(this);
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    public LinkedList<PCommaExpression> getCommaExpression()
    {
        return this._commaExpression_;
    }

    public void setCommaExpression(List<?> list)
    {
        for(PCommaExpression e : this._commaExpression_)
        {
            e.parent(null);
        }
        this._commaExpression_.clear();

        for(Object obj_e : list)
        {
            PCommaExpression e = (PCommaExpression) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._commaExpression_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expression_)
            + toString(this._commaExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        if(this._commaExpression_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        for(ListIterator<PCommaExpression> i = this._commaExpression_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PCommaExpression) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
