/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class ANeqComparison extends PComparison
{
    private PComparison _left_;
    private TNoteq _noteq_;
    private PArith _right_;

    public ANeqComparison()
    {
        // Constructor
    }

    public ANeqComparison(
        @SuppressWarnings("hiding") PComparison _left_,
        @SuppressWarnings("hiding") TNoteq _noteq_,
        @SuppressWarnings("hiding") PArith _right_)
    {
        // Constructor
        setLeft(_left_);

        setNoteq(_noteq_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new ANeqComparison(
            cloneNode(this._left_),
            cloneNode(this._noteq_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANeqComparison(this);
    }

    public PComparison getLeft()
    {
        return this._left_;
    }

    public void setLeft(PComparison node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TNoteq getNoteq()
    {
        return this._noteq_;
    }

    public void setNoteq(TNoteq node)
    {
        if(this._noteq_ != null)
        {
            this._noteq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._noteq_ = node;
    }

    public PArith getRight()
    {
        return this._right_;
    }

    public void setRight(PArith node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._noteq_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._noteq_ == child)
        {
            this._noteq_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PComparison) newChild);
            return;
        }

        if(this._noteq_ == oldChild)
        {
            setNoteq((TNoteq) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PArith) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
