/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import java.util.*;
import scss.analysis.*;

@SuppressWarnings("nls")
public final class AParamOptionalValue extends PParamOptionalValue
{
    private TColon _colon_;
    private PExpression _first_;
    private final LinkedList<PExpression> _rest_ = new LinkedList<PExpression>();

    public AParamOptionalValue()
    {
        // Constructor
    }

    public AParamOptionalValue(
        @SuppressWarnings("hiding") TColon _colon_,
        @SuppressWarnings("hiding") PExpression _first_,
        @SuppressWarnings("hiding") List<?> _rest_)
    {
        // Constructor
        setColon(_colon_);

        setFirst(_first_);

        setRest(_rest_);

    }

    @Override
    public Object clone()
    {
        return new AParamOptionalValue(
            cloneNode(this._colon_),
            cloneNode(this._first_),
            cloneList(this._rest_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParamOptionalValue(this);
    }

    public TColon getColon()
    {
        return this._colon_;
    }

    public void setColon(TColon node)
    {
        if(this._colon_ != null)
        {
            this._colon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colon_ = node;
    }

    public PExpression getFirst()
    {
        return this._first_;
    }

    public void setFirst(PExpression node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public LinkedList<PExpression> getRest()
    {
        return this._rest_;
    }

    public void setRest(List<?> list)
    {
        for(PExpression e : this._rest_)
        {
            e.parent(null);
        }
        this._rest_.clear();

        for(Object obj_e : list)
        {
            PExpression e = (PExpression) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._rest_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colon_)
            + toString(this._first_)
            + toString(this._rest_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colon_ == child)
        {
            this._colon_ = null;
            return;
        }

        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._rest_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colon_ == oldChild)
        {
            setColon((TColon) newChild);
            return;
        }

        if(this._first_ == oldChild)
        {
            setFirst((PExpression) newChild);
            return;
        }

        for(ListIterator<PExpression> i = this._rest_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpression) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
