/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class ARulesetStatement extends PStatement
{
    private PSelectors _selectors_;
    private PBlock _block_;

    public ARulesetStatement()
    {
        // Constructor
    }

    public ARulesetStatement(
        @SuppressWarnings("hiding") PSelectors _selectors_,
        @SuppressWarnings("hiding") PBlock _block_)
    {
        // Constructor
        setSelectors(_selectors_);

        setBlock(_block_);

    }

    @Override
    public Object clone()
    {
        return new ARulesetStatement(
            cloneNode(this._selectors_),
            cloneNode(this._block_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARulesetStatement(this);
    }

    public PSelectors getSelectors()
    {
        return this._selectors_;
    }

    public void setSelectors(PSelectors node)
    {
        if(this._selectors_ != null)
        {
            this._selectors_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._selectors_ = node;
    }

    public PBlock getBlock()
    {
        return this._block_;
    }

    public void setBlock(PBlock node)
    {
        if(this._block_ != null)
        {
            this._block_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._block_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._selectors_)
            + toString(this._block_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._selectors_ == child)
        {
            this._selectors_ = null;
            return;
        }

        if(this._block_ == child)
        {
            this._block_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._selectors_ == oldChild)
        {
            setSelectors((PSelectors) newChild);
            return;
        }

        if(this._block_ == oldChild)
        {
            setBlock((PBlock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
