/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import java.util.*;
import scss.analysis.*;

@SuppressWarnings("nls")
public final class ASelectors extends PSelectors
{
    private PPrefixElement _first_;
    private final LinkedList<PPrefixElement> _rest_ = new LinkedList<PPrefixElement>();
    private final LinkedList<PAttrib> _attrib_ = new LinkedList<PAttrib>();

    public ASelectors()
    {
        // Constructor
    }

    public ASelectors(
        @SuppressWarnings("hiding") PPrefixElement _first_,
        @SuppressWarnings("hiding") List<?> _rest_,
        @SuppressWarnings("hiding") List<?> _attrib_)
    {
        // Constructor
        setFirst(_first_);

        setRest(_rest_);

        setAttrib(_attrib_);

    }

    @Override
    public Object clone()
    {
        return new ASelectors(
            cloneNode(this._first_),
            cloneList(this._rest_),
            cloneList(this._attrib_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASelectors(this);
    }

    public PPrefixElement getFirst()
    {
        return this._first_;
    }

    public void setFirst(PPrefixElement node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public LinkedList<PPrefixElement> getRest()
    {
        return this._rest_;
    }

    public void setRest(List<?> list)
    {
        for(PPrefixElement e : this._rest_)
        {
            e.parent(null);
        }
        this._rest_.clear();

        for(Object obj_e : list)
        {
            PPrefixElement e = (PPrefixElement) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._rest_.add(e);
        }
    }

    public LinkedList<PAttrib> getAttrib()
    {
        return this._attrib_;
    }

    public void setAttrib(List<?> list)
    {
        for(PAttrib e : this._attrib_)
        {
            e.parent(null);
        }
        this._attrib_.clear();

        for(Object obj_e : list)
        {
            PAttrib e = (PAttrib) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._attrib_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._rest_)
            + toString(this._attrib_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._rest_.remove(child))
        {
            return;
        }

        if(this._attrib_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PPrefixElement) newChild);
            return;
        }

        for(ListIterator<PPrefixElement> i = this._rest_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPrefixElement) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PAttrib> i = this._attrib_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAttrib) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
