/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleParam extends PParam
{
    private TDollar _dollar_;
    private PIdent _ident_;
    private PParamOptionalValue _paramOptionalValue_;

    public ASimpleParam()
    {
        // Constructor
    }

    public ASimpleParam(
        @SuppressWarnings("hiding") TDollar _dollar_,
        @SuppressWarnings("hiding") PIdent _ident_,
        @SuppressWarnings("hiding") PParamOptionalValue _paramOptionalValue_)
    {
        // Constructor
        setDollar(_dollar_);

        setIdent(_ident_);

        setParamOptionalValue(_paramOptionalValue_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleParam(
            cloneNode(this._dollar_),
            cloneNode(this._ident_),
            cloneNode(this._paramOptionalValue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleParam(this);
    }

    public TDollar getDollar()
    {
        return this._dollar_;
    }

    public void setDollar(TDollar node)
    {
        if(this._dollar_ != null)
        {
            this._dollar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dollar_ = node;
    }

    public PIdent getIdent()
    {
        return this._ident_;
    }

    public void setIdent(PIdent node)
    {
        if(this._ident_ != null)
        {
            this._ident_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ident_ = node;
    }

    public PParamOptionalValue getParamOptionalValue()
    {
        return this._paramOptionalValue_;
    }

    public void setParamOptionalValue(PParamOptionalValue node)
    {
        if(this._paramOptionalValue_ != null)
        {
            this._paramOptionalValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paramOptionalValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dollar_)
            + toString(this._ident_)
            + toString(this._paramOptionalValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dollar_ == child)
        {
            this._dollar_ = null;
            return;
        }

        if(this._ident_ == child)
        {
            this._ident_ = null;
            return;
        }

        if(this._paramOptionalValue_ == child)
        {
            this._paramOptionalValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dollar_ == oldChild)
        {
            setDollar((TDollar) newChild);
            return;
        }

        if(this._ident_ == oldChild)
        {
            setIdent((PIdent) newChild);
            return;
        }

        if(this._paramOptionalValue_ == oldChild)
        {
            setParamOptionalValue((PParamOptionalValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
