/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class ATilPrefixElement extends PPrefixElement
{
    private TTil _til_;
    private PElement _element_;

    public ATilPrefixElement()
    {
        // Constructor
    }

    public ATilPrefixElement(
        @SuppressWarnings("hiding") TTil _til_,
        @SuppressWarnings("hiding") PElement _element_)
    {
        // Constructor
        setTil(_til_);

        setElement(_element_);

    }

    @Override
    public Object clone()
    {
        return new ATilPrefixElement(
            cloneNode(this._til_),
            cloneNode(this._element_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATilPrefixElement(this);
    }

    public TTil getTil()
    {
        return this._til_;
    }

    public void setTil(TTil node)
    {
        if(this._til_ != null)
        {
            this._til_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._til_ = node;
    }

    public PElement getElement()
    {
        return this._element_;
    }

    public void setElement(PElement node)
    {
        if(this._element_ != null)
        {
            this._element_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._element_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._til_)
            + toString(this._element_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._til_ == child)
        {
            this._til_ = null;
            return;
        }

        if(this._element_ == child)
        {
            this._element_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._til_ == oldChild)
        {
            setTil((TTil) newChild);
            return;
        }

        if(this._element_ == oldChild)
        {
            setElement((PElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
