/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class ATimesFactor extends PFactor
{
    private PFactor _first_;
    private TTimes _mul_;
    private PExpression _second_;

    public ATimesFactor()
    {
        // Constructor
    }

    public ATimesFactor(
        @SuppressWarnings("hiding") PFactor _first_,
        @SuppressWarnings("hiding") TTimes _mul_,
        @SuppressWarnings("hiding") PExpression _second_)
    {
        // Constructor
        setFirst(_first_);

        setMul(_mul_);

        setSecond(_second_);

    }

    @Override
    public Object clone()
    {
        return new ATimesFactor(
            cloneNode(this._first_),
            cloneNode(this._mul_),
            cloneNode(this._second_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATimesFactor(this);
    }

    public PFactor getFirst()
    {
        return this._first_;
    }

    public void setFirst(PFactor node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public TTimes getMul()
    {
        return this._mul_;
    }

    public void setMul(TTimes node)
    {
        if(this._mul_ != null)
        {
            this._mul_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mul_ = node;
    }

    public PExpression getSecond()
    {
        return this._second_;
    }

    public void setSecond(PExpression node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._mul_)
            + toString(this._second_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._mul_ == child)
        {
            this._mul_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PFactor) newChild);
            return;
        }

        if(this._mul_ == oldChild)
        {
            setMul((TTimes) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
