/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class AUrlExpression extends PExpression
{
    private TUrl _url_;

    public AUrlExpression()
    {
        // Constructor
    }

    public AUrlExpression(
        @SuppressWarnings("hiding") TUrl _url_)
    {
        // Constructor
        setUrl(_url_);

    }

    @Override
    public Object clone()
    {
        return new AUrlExpression(
            cloneNode(this._url_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUrlExpression(this);
    }

    public TUrl getUrl()
    {
        return this._url_;
    }

    public void setUrl(TUrl node)
    {
        if(this._url_ != null)
        {
            this._url_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._url_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._url_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._url_ == child)
        {
            this._url_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._url_ == oldChild)
        {
            setUrl((TUrl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
