/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class TAtElse extends Token
{
    public TAtElse()
    {
        super.setText("@else");
    }

    public TAtElse(int line, int pos)
    {
        super.setText("@else");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAtElse(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAtElse(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAtElse text.");
    }
}
