/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class TAtEach extends Token
{
    public TAtEach()
    {
        super.setText("@each");
    }

    public TAtEach(int line, int pos)
    {
        super.setText("@each");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAtEach(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAtEach(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAtEach text.");
    }
}
