/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class TAtIf extends Token
{
    public TAtIf()
    {
        super.setText("@if");
    }

    public TAtIf(int line, int pos)
    {
        super.setText("@if");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAtIf(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAtIf(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAtIf text.");
    }
}
