/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class TAtWhile extends Token
{
    public TAtWhile()
    {
        super.setText("@while");
    }

    public TAtWhile(int line, int pos)
    {
        super.setText("@while");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAtWhile(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAtWhile(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAtWhile text.");
    }
}
