/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class TColoncolon extends Token
{
    public TColoncolon()
    {
        super.setText("::");
    }

    public TColoncolon(int line, int pos)
    {
        super.setText("::");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TColoncolon(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTColoncolon(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TColoncolon text.");
    }
}
