/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class TPoundDefault extends Token
{
    public TPoundDefault()
    {
        super.setText("!default");
    }

    public TPoundDefault(int line, int pos)
    {
        super.setText("!default");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPoundDefault(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPoundDefault(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPoundDefault text.");
    }
}
