/* This file was generated by SableCC (http://www.sablecc.org/). */

package scss.node;

import scss.analysis.*;

@SuppressWarnings("nls")
public final class TTildEq extends Token
{
    public TTildEq()
    {
        super.setText("~=");
    }

    public TTildEq(int line, int pos)
    {
        super.setText("~=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTildEq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTildEq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTildEq text.");
    }
}
